### ISSUE TITLE
Binding Functions

### ISSUE THREAD

**Issue by Lucav17** [akratzel/react-spotify-playlists#2]
I noticed you binded your functions in the constructor. While we can do this, its not always necessary. We can bind them in the render function for event handlers such as onClick={e => { this.function.bind(this)}} or you can bind them directly using the arrow syntax such as function = () => {}

[https://github.com/Schroeder9000/colmar.git](url)

**Comment by akratzel** [comment]
Thanks for the headsup! Changed it accordingly to use arrow functions instead! 👍
